// <auto-generated />
using System;
using DenemeDers.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenemeDers.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20260105202217_MigUp")]
    partial class MigUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenemeDers.Entity.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("DenemeDers.Entity.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumId"));

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("DenemeDers.Entity.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<int>("AKTS")
                        .HasColumnType("int");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OgretimGorevlisiId")
                        .HasColumnType("int");

                    b.Property<int>("SinifDuzeyi")
                        .HasColumnType("int");

                    b.HasKey("DersId");

                    b.HasIndex("BolumId");

                    b.HasIndex("OgretimGorevlisiId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("DenemeDers.Entity.Not", b =>
                {
                    b.Property<int>("NotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotId"));

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("FinalNotu")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("OgretimGorevlisiId")
                        .HasColumnType("int");

                    b.Property<int>("VizeNotu")
                        .HasColumnType("int");

                    b.HasKey("NotId");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("OgretimGorevlisiId");

                    b.ToTable("Notlar");
                });

            modelBuilder.Entity("DenemeDers.Entity.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciId"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Bolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("OgrenciId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("DenemeDers.Entity.OgretimGorevlisi", b =>
                {
                    b.Property<int>("OgretimGorevlisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretimGorevlisiId"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgretimGorevlisiId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BolumId");

                    b.ToTable("OgretimGorevlileri");
                });

            modelBuilder.Entity("DenemeDers.Entity.Ders", b =>
                {
                    b.HasOne("DenemeDers.Entity.Bolum", "Bolum")
                        .WithMany("Dersler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DenemeDers.Entity.OgretimGorevlisi", "OgretimGorevlisi")
                        .WithMany("Dersler")
                        .HasForeignKey("OgretimGorevlisiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bolum");

                    b.Navigation("OgretimGorevlisi");
                });

            modelBuilder.Entity("DenemeDers.Entity.Not", b =>
                {
                    b.HasOne("DenemeDers.Entity.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DenemeDers.Entity.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DenemeDers.Entity.OgretimGorevlisi", "OgretimGorevlisi")
                        .WithMany()
                        .HasForeignKey("OgretimGorevlisiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");

                    b.Navigation("OgretimGorevlisi");
                });

            modelBuilder.Entity("DenemeDers.Entity.Ogrenci", b =>
                {
                    b.HasOne("DenemeDers.Entity.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DenemeDers.Entity.OgretimGorevlisi", b =>
                {
                    b.HasOne("DenemeDers.Entity.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DenemeDers.Entity.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("DenemeDers.Entity.Bolum", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("DenemeDers.Entity.OgretimGorevlisi", b =>
                {
                    b.Navigation("Dersler");
                });
#pragma warning restore 612, 618
        }
    }
}
